site_name: Virginia Tech's Off-campus 101
site_url: https://githubusername.github.io
theme:
  name: material
markdown_extensions:
 - admonition
 - tables
nav:
  - index.md
  - Blacksburg-Transit-App-&-The-Bus-System.md
  - Apartment-Hunting.md
  - The-Food-Situation.md
  - Conclusion.md
